[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "weatherpy-gatekeeper"
version = "0.1.0"
description = "Homework 1 â€” The Gatekeeper"
requires-python = ">=3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
